In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Read in csv file
train = pd.read_csv("records.csv")
train.head()

,User Name,User Openness,User Conscientiousness,User Extraversion,User Agreeableness,User Emotional range,Friend Name,Friend Openness,Friend Conscientiousness,Friend Extraversion,Friend Agreeableness,Friend Emotional range,Friendship Status
0,BeingSalmanKhan,140.674686,278.198646,91.804063,390.844597,48.204554,RahulBilve8,403.159503,502.609485,161.842894,796.568970,191.601912,0
1,BeingSalmanKhan,140.674686,278.198646,91.804063,390.844597,48.204554,ProjectSeestra,971.375022,38.750734,121.118720,118.955003,158.227336,0
2,BeingSalmanKhan,140.674686,278.198646,91.804063,390.844597,48.204554,DanielNewman,655.445518,488.948239,920.505471,946.700446,331.109987,0
3,BeingSalmanKhan,140.674686,278.198646,91.804063,390.844597,48.204554,barrysilbert,834.058255,534.780006,483.078363,203.611373,775.081384,0
4,BeingSalmanKhan,140.674686,278.198646,91.804063,390.844597,48.204554,Survivor_AU,629.263997,741.772604,420.088914,360.690674,651.757763,0

In [3]:
X = train.drop(columns=["User Name","Friend Name","Friendship Status"],axis=1)
X.head()

,User Openness,User Conscientiousness,User Extraversion,User Agreeableness,User Emotional range,Friend Openness,Friend Conscientiousness,Friend Extraversion,Friend Agreeableness,Friend Emotional range
0,140.674686,278.198646,91.804063,390.844597,48.204554,403.159503,502.609485,161.842894,796.568970,191.601912
1,140.674686,278.198646,91.804063,390.844597,48.204554,971.375022,38.750734,121.118720,118.955003,158.227336
2,140.674686,278.198646,91.804063,390.844597,48.204554,655.445518,488.948239,920.505471,946.700446,331.109987
3,140.674686,278.198646,91.804063,390.844597,48.204554,834.058255,534.780006,483.078363,203.611373,775.081384
4,140.674686,278.198646,91.804063,390.844597,48.204554,629.263997,741.772604,420.088914,360.690674,651.757763

In [4]:
Y = train.iloc[:,12:13]
Y.head()

   Friendship Status
0                  0
1                  0
2                  0
3                  0
4                  0

In [5]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(C=1e5, solver='lbfgs',class_weight='balanced')
logreg.fit(X, Y.values.ravel())

LogisticRegression(C=100000.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [6]:
z = logreg.predict(X)
h = logreg.decision_function(X)
# max = 0
# for i in h:
#     print(i)
#         max = i
# print(max)

In [7]:
import pickle
# now you can save it to a file
with open('logisticRegression.pkl', 'wb') as f:
    pickle.dump(logreg, f)

In [8]:
with open('./logisticRegression.pkl', 'rb') as f:
    logreg = pickle.load(f)
train = pd.read_csv("./users.csv")
X = train.drop(columns=["Name"],axis=1)
name_array = list(train["Name"])
X['User Openness'] = data['Openness']
X['User Conscientiousness'] = data['Conscientiousness']
X['User Extraversion'] = data['Extraversion']
X['User Agreeableness'] = data['Agreeableness']
X['User Emotional range'] = data['Emotional range']
X = X.rename(columns={
    'Openness':'Friend Openness',
    'Conscientiousness':'Friend Conscientiousness',
    'Extraversion':'Friend Extraversion',
    'Agreeableness':'Friend Agreeableness',
    'Emotional range':'Friend Emotional range'
    })
X = X[['User Openness','User Conscientiousness','User Extraversion','User Agreeableness','User Emotional range',
    'Friend Openness','Friend Conscientiousness','Friend Extraversion','Friend Agreeableness','Friend Emotional range']]
H = logreg.decision_function(X)
n = len(H)
max_1 = 0
max_2 = 0
max_3 = 0
for i in range(n):
    if(H[i]>H[max_1]):
        max_3 = max_2
        max_2 = max_1
        max_1 = i
    elif(H[i]>H[max_2]):
        max_3 = max_2
        max_2 = i
    elif(H[i]>H[max_3]):
        max_3 = i
return [name_array[max_1], name_array[max_2], name_array[max_3]]

NameError: name 'data' is not defined

In [9]:
import tweepy
import requests
import json
import os.path
import numpy as np
import pandas as pd
import pickle

consumer_key = 'Kt6WNY1DPSBLPkrFzQoE0TV6h'
consumer_secret = 'UUTUOUgIZ0uBijCWay4Y1j6Spb0JlYBFvngB4a1WeC1KK9kQmg'
access_token = '2951964404-Thlks6h0r7mboOf36Yk3dp1YCKgHYho0QdY7uCD'
access_token_secret = 'kBInoOMXY362LkAvRq87geWpqtdIxL93jOxviICVmFm1k'
ibmAuthoziation = 'mYMCHtOw3tfKY2ulgkbR2qv_Jc1UP26w3bN5Gf4zXxFP'
ibmBaseUrl = 'https://gateway-lon.watsonplatform.net/personality-insights/api'
ibmPersonalityUrl = ibmBaseUrl + '/v3/profile?version=2017-10-13'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
# Calling api
api = tweepy.API(auth)

def get_tweets(username):
    if(os.path.isfile('./Dataset/' + username + '.txt')):
        return
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    # # Calling api
    api = tweepy.API(auth)
    # 200 tweets to be extracted
    number_of_tweets=2000
    tweets = api.user_timeline(screen_name=username,count=number_of_tweets,tweet_mode="extended")

    f = open("./Dataset/" + username + ".txt", "w")
    for tweet in tweets:
        f.write(tweet.full_text + '\n')
    f.close()

def get_traits(username):
    if(os.path.isfile('./Features/' + username + '.json')):
        return
    path = "./Dataset/" + username + ".txt"
    data = open(path, 'rb').read()
    res = requests.post(
            ibmPersonalityUrl,
            auth=('apikey',ibmAuthoziation),
            headers={
                'Content-Type':'text/plain',
                'Accept':'application/json'
                },
            data = data
            )
    os.remove('./Dataset/' + username + '.txt')
    return res.json()

def cleanData(jsonResponse,user):
    try:
        big5 = jsonResponse['personality']
        user = { 'Name' : user}
        for i in big5:
            user[i['name']]=i['percentile']*100
        return user
    except:
        return False

def run_logistic_regression(data):
    with open('./logisticRegression.pkl', 'rb') as f:
        logreg = pickle.load(f)
    train = pd.read_csv("./users.csv")
    X = train.drop(columns=["Name"],axis=1)
    name_array = list(train["Name"])
    X['User Openness'] = data['Openness']
    X['User Conscientiousness'] = data['Conscientiousness']
    X['User Extraversion'] = data['Extraversion']
    X['User Agreeableness'] = data['Agreeableness']
    X['User Emotional range'] = data['Emotional range']
    X = X.rename(columns={
        'Openness':'Friend Openness',
        'Conscientiousness':'Friend Conscientiousness',
        'Extraversion':'Friend Extraversion',
        'Agreeableness':'Friend Agreeableness',
        'Emotional range':'Friend Emotional range'
        })
    X = X[['User Openness','User Conscientiousness','User Extraversion','User Agreeableness','User Emotional range',
        'Friend Openness','Friend Conscientiousness','Friend Extraversion','Friend Agreeableness','Friend Emotional range']]
    H = logreg.decision_function(X)
    n = len(H)
    max_1 = 0
    max_2 = 0
    max_3 = 0
    for i in range(n):
        if(H[i]>H[max_1]):
            max_3 = max_2
            max_2 = max_1
            max_1 = i
        elif(H[i]>H[max_2]):
            max_3 = max_2
            max_2 = i
        elif(H[i]>H[max_3]):
            max_3 = i
    return [name_array[max_1], name_array[max_2], name_array[max_3]]

def test(user):
    get_tweets(user)
    personality = get_traits(user)
    data = cleanData(personality,user)
    # data = ['fjjf']
#     return data
    if(data):
        return run_logistic_regression(data)

In [10]:
test("RahulGandhi")

['Dhayarajesh', 'EnduranSobebo', 'chrismlacy']